name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.group == 'Downstream' }}
    strategy:
      #fail-fast: false
      matrix:
        group:
          - InterfaceI
          - InterfaceII
          - InterfaceIII
          - Integrators_I
          - AlgConvergence_I
          - AlgConvergence_II
          - AlgConvergence_III
          - Downstream
          - ODEInterfaceRegression
          - Multithreading
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        id: cache-julia
        uses: actions/cache@v2
        with:
          # If you use a different target dir, you may want to update the cache key to include that info.
          # actions/cache does not provide an option to specify the target dir for restoring the cache,
          # so you may run into issues where the target dir of the build-julia action mismatches the cached directory.
          path: ~/julia

          # Note that this cache key will not work with branches
          # because there could be new commits after the cache has been created.
          key: ${{ runner.os }}-${{ matrix.julia-ref }}
      - name: Build Julia
        # Only rebuild Julia if there is no cache hit.
        if: steps.cache-julia.outputs.cache-hit != 'true'
        uses: julia-actions/build-julia@v1
        with:
          # The value that is passed to git checkout, e.g. a tag, branch or a commit.
          #
          # Default: master
          ref: 27f01f2771b77ffad4eb4b0668d1ae0893c3fe93

          # The value that is passed to git clone. If you want to build Julia from a fork of yours,
          # you can change this value to https://github.com/YOUR_GITHUB_NAME/julia.git.
          #
          # Default: https://github.com/JuliaLang/julia.git
          source-repo: https://github.com/IanButterworth/julia.git
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        env:
          GROUP: ${{ matrix.group }}
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
